apiVersion: v1
kind: Namespace
metadata:
  name: autocura
  labels:
    name: autocura
    environment: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autocura-config
  namespace: autocura
data:
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "production"
  OTEL_SERVICE_NAME: "autocura"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://opentelemetry-collector.monitoring.svc.cluster.local:4317"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_TRACES_SAMPLER: "parentbased_traceidratio"
  OTEL_TRACES_SAMPLER_ARG: "0.1"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_LOGS_EXPORTER: "otlp"
  OTEL_PROPAGATORS: "b3,baggage,tracecontext"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autocura-memoria
  namespace: autocura
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autocura-modelos
  namespace: autocura
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard
