apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: autocura-rolebinding
  namespace: autocura
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: autocura-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: autocura 