{{- if .Values.grafana.enabled }}
{{- if .Values.grafana.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "diagnostico.fullname" . }}-grafana
  labels:
    {{- include "diagnostico.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  accessModes:
    {{- range .Values.grafana.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size | quote }}
  {{- if .Values.grafana.persistence.storageClass }}
  storageClassName: {{ .Values.grafana.persistence.storageClass }}
  {{- end }}
{{- end }}
{{- end }} 