{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "diagnostico.fullname" . }}-datasource
  labels:
    {{- include "diagnostico.labels" . | nindent 4 }}
    grafana_datasource: "1"
data:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server
        isDefault: true
        editable: false
        version: 1
        jsonData:
          timeInterval: "5s"
          queryTimeout: "30s"
          httpMethod: "POST"
          manageAlerts: true
          alertmanagerUid: "alertmanager"
        secureJsonData:
          httpHeaderName1: "X-Scope-OrgID"
        uid: prometheus
{{- end }} 