{{- if .Values.grafana.enabled }}
{{- if .Values.grafana.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "diagnostico.fullname" . }}-grafana
  labels:
    {{- include "diagnostico.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  podSelector:
    matchLabels:
      {{- include "diagnostico.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: grafana
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        {{- if .Values.grafana.networkPolicy.ingress.namespaceSelector }}
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.grafana.networkPolicy.ingress.namespaceSelector | nindent 14 }}
        {{- end }}
        {{- if .Values.grafana.networkPolicy.ingress.podSelector }}
        - podSelector:
            matchLabels:
              {{- toYaml .Values.grafana.networkPolicy.ingress.podSelector | nindent 14 }}
        {{- end }}
      ports:
        - protocol: TCP
          port: 3000
  egress:
    - to:
        {{- if .Values.grafana.networkPolicy.egress.namespaceSelector }}
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.grafana.networkPolicy.egress.namespaceSelector | nindent 14 }}
        {{- end }}
        {{- if .Values.grafana.networkPolicy.egress.podSelector }}
        - podSelector:
            matchLabels:
              {{- toYaml .Values.grafana.networkPolicy.egress.podSelector | nindent 14 }}
        {{- end }}
      ports:
        - protocol: TCP
          port: 9090
        - protocol: TCP
          port: 9093
{{- end }}
{{- end }} 