{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "diagnostico.fullname" . }}-grafana
  labels:
    {{- include "diagnostico.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
type: Opaque
data:
  admin-password: {{ .Values.grafana.adminPassword | b64enc | quote }}
  {{- if .Values.grafana.alertmanager.slack.webhookUrl }}
  slack-webhook-url: {{ .Values.grafana.alertmanager.slack.webhookUrl | b64enc | quote }}
  {{- end }}
{{- end }} 