apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: autocura-rolebinding
  namespace: autocura
subjects:
- kind: ServiceAccount
  name: autocura-sa
  namespace: autocura
roleRef:
  kind: Role
  name: autocura-role
  apiGroup: rbac.authorization.k8s.io
