apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- network-policy.yaml
- pdb.yaml
- resource-quota.yaml
- limit-range.yaml
- rbac.yaml
- pv.yaml

commonLabels:
  app.kubernetes.io/name: autocura
  app.kubernetes.io/part-of: autocura-system
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  kubernetes.io/change-cause: "Initial deployment" 