apiVersion: v1
kind: PersistentVolume
metadata:
  name: autocura-memoria-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/autocura/memoria
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: autocura-modelos-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/autocura/modelos 