apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: autocura-role
  namespace: autocura
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: autocura-role-binding
  namespace: autocura
subjects:
- kind: ServiceAccount
  name: autocura-sa
  namespace: autocura
roleRef:
  kind: Role
  name: autocura-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autocura-sa
  namespace: autocura 