apiVersion: v1
kind: ResourceQuota
metadata:
  name: autocura-quota
  namespace: autocura
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    persistentvolumeclaims: "10"
    services.loadbalancers: "1"
    services.nodeports: "0" 