apiVersion: apps/v1
kind: Deployment
metadata:
  name: autocura-app
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: autocura
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: autocura
    spec:
      containers:
      - name: autocura
        image: autocura:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: REDIS_HOST
          value: "redis-master"
        - name: REDIS_PORT
          value: "6379"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: autocura-config
---
apiVersion: v1
kind: Service
metadata:
  name: autocura-service
  namespace: production
spec:
  selector:
    app: autocura
  ports:
  - port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autocura-hpa
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autocura-app
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autocura-ingress
  namespace: production
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - api.autocura.com
    secretName: autocura-tls
  rules:
  - host: api.autocura.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: autocura-service
            port:
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: autocura-config
  namespace: production
data:
  config.yaml: |
    app:
      name: autocura
      environment: production
      debug: false
      log_level: INFO
    cache:
      redis:
        host: redis-master
        port: 6379
        db: 0
    security:
      encryption:
        key_rotation_days: 30
      anomaly_detection:
        window_size: 100
        contamination: 0.1
    monitoring:
      prometheus:
        enabled: true
        path: /metrics
      grafana:
        enabled: true
        dashboard: autocura
      loki:
        enabled: true
        url: http://loki:3100 