apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-config
  namespace: monitoring
data:
  opentelemetry-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      memory_limiter:
        check_interval: 1s
        limit_mib: 1500
        spike_limit_mib: 512
      resource:
        attributes:
          service.name: "autocura"
          deployment.environment: "production"

    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
        namespace: "autocura"
        resource_to_telemetry_conversion:
          enabled: true
      jaeger:
        endpoint: "jaeger-collector.monitoring.svc.cluster.local:14250"
        tls:
          insecure: true
      logging:
        loglevel: info

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [jaeger, logging]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch, resource]
          exporters: [prometheus, logging]

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      pprof:
        endpoint: 0.0.0.0:1777
      zpages:
        endpoint: 0.0.0.0:55679 