apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'autocura'
        static_configs:
          - targets: ['autocura-api.autocura.svc.cluster.local:9090']
        metrics_path: '/metrics'
        
      - job_name: 'autocura-monitor'
        static_configs:
          - targets: ['autocura-monitor.autocura.svc.cluster.local:9090']
        metrics_path: '/metrics'
        
      - job_name: 'autocura-observador'
        static_configs:
          - targets: ['autocura-observador.autocura.svc.cluster.local:8080']
        metrics_path: '/metrics'

  rules.yml: |
    groups:
    - name: autocura
      rules:
      - alert: HighCPUUsage
        expr: container_cpu_usage_seconds_total{container="api"} > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Alto uso de CPU no container API"
          description: "Container {{ $labels.container }} está usando {{ $value }}% de CPU"

      - alert: HighMemoryUsage
        expr: container_memory_usage_bytes{container="api"} > 400Mi
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Alto uso de memória no container API"
          description: "Container {{ $labels.container }} está usando {{ $value }} bytes de memória"

      - alert: HighLatency
        expr: http_request_duration_seconds{quantile="0.9"} > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Alta latência nas requisições HTTP"
          description: "90% das requisições estão demorando mais que 1s"

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Alta taxa de erros HTTP"
          description: "Taxa de erros 5xx está acima de 5%"

      - alert: PodRestarting
        expr: kube_pod_container_status_restarts_total{container="api"} > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container reiniciando frequentemente"
          description: "Container {{ $labels.container }} reiniciou {{ $value }} vezes"

      - alert: LowDiskSpace
        expr: node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} < 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Espaço em disco baixo"
          description: "Apenas {{ $value | humanizePercentage }} de espaço disponível"

      - alert: HighNetworkErrors
        expr: rate(node_network_transmit_errs_total[5m]) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Erros de rede detectados"
          description: "Erros de transmissão de rede detectados no nó {{ $labels.instance }}"

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: autocura
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: autocura
  namespaceSelector:
    matchNames:
      - autocura
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics 