apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: autocura
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: autocura
  namespaceSelector:
    matchNames:
      - autocura
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics 