global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'process'
    static_configs:
      - targets: ['localhost:9100']
    metrics_path: '/metrics'
    params:
      collect[]:
        - process
        - process_cpu
        - process_mem
        - process_disk
        - process_net
        - process_fd
        - process_vm
        - process_sched
        - process_start_time
        - process_threads
        - process_context_switches
        - process_cpu_seconds_total
        - process_memory_bytes
        - process_open_fds
        - process_resident_memory_bytes
        - process_start_time_seconds
        - process_threads
        - process_virtual_memory_bytes
        - process_virtual_memory_max_bytes 