apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoramento
  namespace: autocura
  labels:
    app: monitoramento
    component: autocura
    app.kubernetes.io/component: monitoramento
    app.kubernetes.io/part-of: autocura
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monitoramento
      app.kubernetes.io/component: monitoramento
      app.kubernetes.io/part-of: autocura
      app.kubernetes.io/managed-by: kustomize
  template:
    metadata:
      labels:
        app: monitoramento
        app.kubernetes.io/component: monitoramento
        app.kubernetes.io/part-of: autocura
        app.kubernetes.io/managed-by: kustomize
    spec:
      serviceAccountName: autocura-sa
      containers:
      - name: monitoramento
<<<<<<< HEAD
        image: localhost:5000/autocura/monitoramento:latest
        imagePullPolicy: Always
=======
        image: localhost:5000/monitoramento:latest
        imagePullPolicy: IfNotPresent
>>>>>>> origin/main
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
        env:
        - name: CONFIG_MAP
          value: monitoramento-config
        - name: LOG_LEVEL
          value: INFO
<<<<<<< HEAD
=======
        - name: WILL_URL
          value: "http://will:5000"
>>>>>>> origin/main
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: data-volume
          mountPath: /app/data
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: config-volume
        configMap:
          name: monitoramento-config
      - name: data-volume
        persistentVolumeClaim:
          claimName: autocura-models
