apiVersion: v1
kind: ConfigMap
metadata:
  name: guardiao-cognitivo-config
  labels:
    app: autocura
    component: guardiao-cognitivo
data:
  DIAGNOSTICO_SERVICE_URL: "http://diagnostico:8080"
  ACAO_SERVICE_URL: "http://gerador-acoes:8080" # Corrigido para a porta 8080, conforme análise dos serviços existentes
  MONITORAMENTO_SERVICE_URL: "http://monitoramento:8080" # Adicionado para consistência com o código do Guardião
  EMERGENCY_PROTOCOL_ENABLED: "true"
