apiVersion: v1
kind: Service
metadata:
  name: guardiao-cognitivo
  labels: # Adicionado labels para consistência
    app: autocura
    component: guardiao-cognitivo
spec:
  selector:
    component: guardiao-cognitivo
  ports:
    - protocol: TCP
      port: 8081 # Porta que o serviço expõe no cluster
      targetPort: 8081 # Porta do container, conforme deployment.yaml e código
  type: ClusterIP
