version: '3.8'

services:
  # Serviço de Autocorreção
  autocorrection:
    build:
      context: .
      dockerfile: src/autocorrection/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
    depends_on:
      - diagnostico
      - gerador_acoes
    networks:
      - autocura_network

  # Serviço de Diagnóstico
  diagnostico:
    build:
      context: .
      dockerfile: src/diagnostico/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
    networks:
      - autocura_network

  # Serviço Gerador de Ações
  gerador_acoes:
    build:
      context: .
      dockerfile: src/GeradorAcoes/Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
    networks:
      - autocura_network

  # Serviço de Monitoramento
  monitoramento:
    build:
      context: .
      dockerfile: src/monitoramento/Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
    networks:
      - autocura_network

  # Serviço de Observabilidade
  observabilidade:
    build:
      context: .
      dockerfile: src/observabilidade/Dockerfile
    ports:
      - "5004:5004"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
    networks:
      - autocura_network

  # Serviço de Portal
  portal:
    build:
      context: .
      dockerfile: src/portal/Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
    depends_on:
      - autocorrection
      - diagnostico
      - gerador_acoes
      - monitoramento
      - observabilidade
    networks:
      - autocura_network

networks:
  autocura_network:
    driver: bridge

volumes:
  will_data:
  diagnostico_data:
  gerador_acoes_data:
  observabilidade_data:
  monitoramento_data:
  executor_data:
  guardiao_cognitivo_data: 