version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/services/api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  monitor:
    build:
      context: .
      dockerfile: docker/services/monitor/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  observador:
    build:
      context: .
      dockerfile: docker/services/observador/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  validador:
    build:
      context: .
      dockerfile: docker/services/validador/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  guardiao:
    build:
      context: .
      dockerfile: docker/services/guardiao/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  gerador:
    build:
      context: .
      dockerfile: docker/services/gerador/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  diagnostico:
    build:
      context: .
      dockerfile: docker/services/diagnostico/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  tests:
    build:
      context: .
      dockerfile: docker/tests/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

volumes:
  redis_data:

networks:
  autocura-network:
    driver: bridge 