server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: testes
    static_configs:
      - targets:
          - localhost
        labels:
          job: testes
          __path__: /var/log/testes.log

  - job_name: aplicacao
    static_configs:
      - targets:
          - localhost
        labels:
          job: aplicacao
          __path__: /var/log/aplicacao.log

  - job_name: monitoramento
    static_configs:
      - targets:
          - localhost
        labels:
          job: monitoramento
          __path__: /var/log/monitoramento.log 