{{- if .Values.grafana.enabled }}
{{- if .Values.grafana.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "diagnostico.fullname" . }}-grafana
  labels:
    {{- include "diagnostico.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  {{- if .Values.grafana.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.grafana.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.grafana.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.grafana.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "diagnostico.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: grafana
{{- end }}
{{- end }} 