{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "diagnostico.fullname" . }}-alertrules
  labels:
    {{- include "diagnostico.labels" . | nindent 4 }}
    grafana_alertrules: "1"
data:
  alertrules.yaml: |-
    groups:
      - name: diagnostico
        rules:
          - alert: HighRequestLatency
            expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m]) > 0.5
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High request latency on {{ $labels.instance }}"
              description: "Request latency is above 500ms (current value: {{ $value }}s)"
              dashboard_url: "http://grafana/d/diagnostico/diagnostico"

          - alert: HighErrorRate
            expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "High error rate on {{ $labels.instance }}"
              description: "Error rate is above 5% (current value: {{ $value }})"
              dashboard_url: "http://grafana/d/diagnostico/diagnostico"

          - alert: HighCPUUsage
            expr: rate(process_cpu_seconds_total[5m]) * 100 > 80
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage on {{ $labels.instance }}"
              description: "CPU usage is above 80% (current value: {{ $value }}%)"
              dashboard_url: "http://grafana/d/diagnostico/diagnostico"

          - alert: HighMemoryUsage
            expr: (process_resident_memory_bytes / container_memory_usage_bytes) * 100 > 80
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "High memory usage on {{ $labels.instance }}"
              description: "Memory usage is above 80% (current value: {{ $value }}%)"
              dashboard_url: "http://grafana/d/diagnostico/diagnostico"

          - alert: ServiceDown
            expr: up == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Service {{ $labels.instance }} is down"
              description: "Service has been down for more than 1 minute"
              dashboard_url: "http://grafana/d/diagnostico/diagnostico"
{{- end }} 