apiVersion: apps/v1
kind: Deployment
metadata:
  name: autocura
  namespace: autocura
spec:
  replicas: 3
  selector:
    matchLabels:
      app: autocura
  template:
    metadata:
      labels:
        app: autocura
    spec:
      containers:
      - name: api
        image: autocura/api:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: DEBUG
          value: "false"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: autocura-config
---
apiVersion: v1
kind: Service
metadata:
  name: autocura
  namespace: autocura
spec:
  selector:
    app: autocura
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autocura
  namespace: autocura
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - api.autocura.com
    secretName: autocura-tls
  rules:
  - host: api.autocura.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: autocura
            port:
              number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autocura
  namespace: autocura
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autocura
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 