{
 "title": "Dashboard de Testes",
 "tags": [
  "testes",
  "monitoramento"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Tempo Médio de Execução dos Testes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(pytest_execution_time_seconds_sum[5m]) / rate(pytest_execution_time_seconds_count[5m])",
     "legendFormat": "Tempo Médio de Execução"
    }
   ]
  },
  {
   "title": "Estatísticas de Testes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "pytest_tests_total", "legendFormat": "Total de Testes" },
    { "expr": "pytest_tests_passed", "legendFormat": "Testes Passados" },
    { "expr": "pytest_tests_failed", "legendFormat": "Testes Falhados" }
   ]
  },
  {
   "title": "Cobertura de Código",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "pytest_coverage_percentage", "legendFormat": "Cobertura de Código" }
   ]
  }
 ]
}