apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: observabilidade-alertmanager
  namespace: autocura
spec:
  serviceAccountName: alertmanager
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  alertmanagerConfigSelector: {}
  alertmanagerConfigNamespaceSelector: {}
  configSecret: alertmanager-config 