apiVersion: v1
kind: ServiceAccount
metadata:
  name: observabilidade
  namespace: autocura
  labels:
    app.kubernetes.io/name: observabilidade
    app.kubernetes.io/part-of: autocura
automountServiceAccountToken: false 