cluster.name: "docker-cluster"
network.host: 0.0.0.0

# Configurações de memória
bootstrap.memory_lock: true
"ES_JAVA_OPTS": "-Xms512m -Xmx512m"

# Configurações de segurança
xpack.security.enabled: false
xpack.monitoring.enabled: true
xpack.watcher.enabled: false

# Configurações de descoberta
discovery.type: single-node

# Configurações de HTTP
http.port: 9200
http.cors.enabled: true
http.cors.allow-origin: "*"

# Configurações de índices
action.destructive_requires_name: true
action.auto_create_index: false

# Configurações de logs
path.logs: /usr/share/elasticsearch/logs

# Configurações de snapshots
path.repo: ["/usr/share/elasticsearch/snapshots"]

# Configurações de plugins
plugin.mandatory: analysis-icu,analysis-phonetic

# Configurações de cache
indices.breaker.total.use_real_memory: false
indices.breaker.total.limit: 70%
indices.breaker.fielddata.limit: 40%
indices.breaker.request.limit: 40%

# Configurações de threads
thread_pool.search.size: 5
thread_pool.search.queue_size: 1000
thread_pool.write.size: 5
thread_pool.write.queue_size: 1000

# Configurações de timeout
search.default_search_timeout: 30s
search.default_keep_alive: 5m

# Configurações de retenção
action.destructive_requires_name: true
action.auto_create_index: false 