apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    version: 1
    jsonData:
      timeInterval: 5s
      queryTimeout: 30s
      httpMethod: POST
      manageAlerts: true
      alertmanagerUid: alertmanager
    secureJsonData:
      httpHeaderName1: "X-Scope-OrgID"
      httpHeaderValue1: "1"

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: false
    version: 1
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: prometheus
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"
    secureJsonData:
      httpHeaderName1: "X-Scope-OrgID"
      httpHeaderValue1: "1" 