apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
<<<<<<< HEAD

namespace: autocura

=======
namespace: autocura
>>>>>>> origin/main
resources:
- alertmanager.yaml
- service.yaml
- configmap.yaml
- ingress.yaml
<<<<<<< HEAD

commonLabels:
  app.kubernetes.io/name: alertmanager
  app.kubernetes.io/part-of: monitoramento 
=======
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: monitoramento
>>>>>>> origin/main
