apiVersion: v1
kind: Service
metadata:
  name: monitoramento
  namespace: autocura
  labels:
    app: monitoramento
    component: autocura
spec:
  selector:
    app: monitoramento
  ports:
  - port: 8080
    targetPort: http
    name: http
  type: ClusterIP
