apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
<<<<<<< HEAD

namespace: autocura

=======
namespace: autocura
>>>>>>> origin/main
resources:
- serviceaccount.yaml
- role.yaml
- rolebinding.yaml
- configmap.yaml
- service.yaml
- deployment.yaml
- pvc.yaml
- ingress.yaml
<<<<<<< HEAD

=======
>>>>>>> origin/main
labels:
- pairs:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: autocura
<<<<<<< HEAD

commonAnnotations:
  description: "Prometheus para o Sistema de Autocura Cognitiva" 
=======
commonAnnotations:
  description: Prometheus para o Sistema de Autocura Cognitiva
>>>>>>> origin/main
