global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'monitor'
    static_configs:
      - targets: ['monitor:9090']
    metrics_path: '/metrics'

  - job_name: 'observador'
    static_configs:
      - targets: ['observador:8080']
    metrics_path: '/metrics'

  - job_name: 'validador'
    static_configs:
      - targets: ['validador:8080']
    metrics_path: '/metrics'

  - job_name: 'guardiao'
    static_configs:
      - targets: ['guardiao:8080']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml" 