apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: autocura
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      tls:
        certificate: /certs/domain.crt
        key: /certs/domain.key
      headers:
        X-Content-Type-Options: [nosniff] 