# /home/ubuntu/Autocura_project/Autocura/config/api_endpoints.yaml
# Endpoints oficiais e de fallback para as APIs externas
# Estes valores podem ser usados como padrão se não forem sobrescritos via Helm values.

apis:
  news:
    primary_endpoint: "https://gdeltproject.org/api/v2/doc" # Exemplo para GDELT (requer adaptação no parser)
    fallback_endpoint: "https://newsapi.org/v2/everything" # Exemplo para NewsAPI.org
    # O código atual em data_sources.py usa um genérico "https://api.example-events.com/v1/news"
    # e espera que o endpoint completo seja passado ou configurado.
    # Para consistência, o data_sources.py deve ser adaptado para usar estes endpoints.

  finance:
    primary_endpoint: "https://dataservices.imf.org/REST/SDMX_JSON.svc" # Exemplo para IMF Data API
    fallback_endpoint: "https://api.worldbank.org/v2/country/all/indicator" # Exemplo para World Bank Open Data
    # O código atual em data_sources.py usa um genérico "https://api.finance-data.com/v1/indicators"

  climate:
    primary_endpoint: "https://api.openweathermap.org/data/2.5/weather" # Exemplo para OpenWeatherMap (requer /forecast ou /climate para dados mais abrangentes)
    fallback_endpoint: "https://www.ncdc.noaa.gov/cdo-web/api/v2/data" # Exemplo para NOAA Climate API
    # O código atual em data_sources.py usa um genérico "https://api.climate-service.com/v4/climate"

