apiVersion: apps/v1
kind: Deployment
metadata:
  name: diagnostico
  namespace: autocura
  labels:
    app: diagnostico
    component: autocura
    app.kubernetes.io/component: diagnostico
    app.kubernetes.io/part-of: autocura
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diagnostico
      app.kubernetes.io/component: diagnostico
      app.kubernetes.io/part-of: autocura
      app.kubernetes.io/managed-by: kustomize
  template:
    metadata:
      labels:
        app: diagnostico
        app.kubernetes.io/component: diagnostico
        app.kubernetes.io/part-of: autocura
        app.kubernetes.io/managed-by: kustomize
    spec:
      serviceAccountName: autocura-sa
      containers:
      - name: diagnostico
<<<<<<< HEAD
        image: localhost:5000/autocura/diagnostico:latest
        imagePullPolicy: Always
=======
        image: localhost:5000/diagnostico:latest
        imagePullPolicy: IfNotPresent
>>>>>>> origin/main
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 1500m
            memory: 1.5Gi
          requests:
            cpu: 750m
            memory: 768Mi
        env:
        - name: MONITORAMENTO_URL
          value: "http://monitoramento:8080"
        - name: CONFIG_MAP
          value: diagnostico-config
        - name: LOG_LEVEL
          value: INFO
<<<<<<< HEAD
=======
        - name: WILL_URL
          value: "http://will:5000"
>>>>>>> origin/main
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: models-volume
          mountPath: /app/models
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 90
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: config-volume
        configMap:
          name: diagnostico-config
      - name: models-volume
        persistentVolumeClaim:
          claimName: autocura-models
