apiVersion: v1
kind: Service
metadata:
  name: diagnostico
  namespace: autocura
  labels:
    app: diagnostico
    component: autocura
    app.kubernetes.io/name: diagnostico
    app.kubernetes.io/part-of: autocura
  annotations:
    description: Configurações de diagnóstico do Sistema de Autocura Cognitiva
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: diagnostico
