apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
<<<<<<< HEAD

=======
>>>>>>> origin/main
resources:
- ../../base
- ../../components/monitoramento
- ../../components/diagnostico
- ../../components/gerador
- ../../components/observabilidade
<<<<<<< HEAD

namespace: autocura

labels:
- pairs:
    environment: development
    app.kubernetes.io/environment: development
  includeSelectors: false

=======
namespace: autocura
labels:
- pairs:
    app.kubernetes.io/environment: development
    environment: development
>>>>>>> origin/main
patches:
- path: resources-patch.yaml
  target:
    kind: Deployment
    labelSelector: app.kubernetes.io/part-of=autocura
<<<<<<< HEAD

configMapGenerator:
- name: environment-config
  literals:
=======
configMapGenerator:
- literals:
>>>>>>> origin/main
  - ENV=development
  - DEBUG=true
  - LOG_LEVEL=DEBUG
  - POD_DISRUPTION_BUDGET=1
<<<<<<< HEAD

# Configuração de imagens com nomes completos para acesso externo
images:
- name: autocura/monitoramento
  newName: localhost:5000/autocura/monitoramento
  newTag: latest
- name: autocura/diagnostico
  newName: localhost:5000/autocura/diagnostico
  newTag: latest
- name: autocura/gerador
  newName: localhost:5000/autocura/gerador
  newTag: latest
- name: autocura/observabilidade
  newName: localhost:5000/autocura/observabilidade
  newTag: latest
=======
  name: environment-config
# Configuração de imagens com nomes completos para acesso externo
images:
- name: registry.registry.svc.cluster.local:5000/autocura/monitoramento
  newTag: dev
- name: registry.registry.svc.cluster.local:5000/autocura/diagnostico
  newTag: dev
- name: registry.registry.svc.cluster.local:5000/autocura/gerador
  newTag: dev
- name: registry.registry.svc.cluster.local:5000/autocura/observabilidade
  newTag: dev
>>>>>>> origin/main
