apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gerador-rolebinding
  namespace: autocura
  labels:
    app.kubernetes.io/name: gerador
    app.kubernetes.io/part-of: components
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gerador-role
subjects:
- kind: ServiceAccount
  name: gerador
  namespace: autocura 