apiVersion: v1
kind: ServiceAccount
metadata:
  name: gerador
  namespace: autocura
  labels:
    app.kubernetes.io/name: gerador
    app.kubernetes.io/part-of: autocura
automountServiceAccountToken: false 