apiVersion: v1
kind: Service
metadata:
  name: gerador
  namespace: autocura
  labels:
    app: gerador
    component: autocura
    app.kubernetes.io/name: gerador
    app.kubernetes.io/part-of: autocura
  annotations:
    description: Configurações do gerador de ações do Sistema de Autocura Cognitiva
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: gerador
