apiVersion: v1
kind: Service
metadata:
  name: consciencia-situacional
  labels:
    app: consciencia-situacional
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: consciencia-situacional 