apiVersion: v1
kind: ServiceAccount
metadata:
  name: diagnostico
  namespace: autocura
  labels:
    app.kubernetes.io/name: diagnostico
    app.kubernetes.io/part-of: components
automountServiceAccountToken: false 