apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
<<<<<<< HEAD

namespace: autocura

=======
namespace: autocura
>>>>>>> origin/main
resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- pvc.yaml
- secrets.yaml
- ingress.yaml
- serviceaccount.yaml
<<<<<<< HEAD

labels:
- pairs:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: autocura

commonAnnotations:
  description: "Grafana para o Sistema de Autocura Cognitiva"

commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/part-of: monitoramento 
=======
commonAnnotations:
  description: Grafana para o Sistema de Autocura Cognitiva
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: monitoramento
>>>>>>> origin/main
