cluster.name: "autocura"
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Configurações de memória
bootstrap.memory_lock: true
bootstrap.system_call_filter: false

# Configurações de segurança
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.http.ssl.enabled: true

# Configurações de índice
action.auto_create_index: true
action.destructive_requires_name: true

# Configurações de logging
logger.level: INFO
logger.type: console

# Configurações de discovery
discovery.type: single-node

# Configurações de JVM
bootstrap.memory_lock: true
bootstrap.system_call_filter: false

# Configurações de cache
indices.breaker.total.use_real_memory: true
indices.breaker.total.limit: 70%
indices.breaker.fielddata.limit: 40%
indices.breaker.request.limit: 40%

# Configurações de thread pools
thread_pool.search.size: 5
thread_pool.search.queue_size: 1000
thread_pool.write.size: 5
thread_pool.write.queue_size: 1000

# Configurações de circuit breaker
indices.breaker.total.limit: 70%
indices.breaker.fielddata.limit: 40%
indices.breaker.request.limit: 40%

# Configurações de recovery
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 85%
cluster.routing.allocation.disk.watermark.high: 90%
cluster.routing.allocation.disk.watermark.flood_stage: 95%

# Configurações de snapshot
path.repo: ["/usr/share/elasticsearch/snapshots"]

# Configurações de monitoramento
xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true 