apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: autocura
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32000
    protocol: TCP
  selector:
    app: registry 