{{- if .Values.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "diagnostico.fullname" . }}-grafana
  labels:
    {{- include "diagnostico.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  replicas: {{ .Values.grafana.replicaCount }}
  selector:
    matchLabels:
      {{- include "diagnostico.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: grafana
  template:
    metadata:
      labels:
        {{- include "diagnostico.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: grafana
    spec:
      serviceAccountName: {{ include "diagnostico.fullname" . }}-grafana
      securityContext:
        {{- toYaml .Values.grafana.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-grafana
          securityContext:
            {{- toYaml .Values.grafana.securityContext | nindent 12 }}
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.adminUser | quote }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "diagnostico.fullname" . }}-grafana
                  key: admin-password
            - name: GF_INSTALL_PLUGINS
              value: {{ .Values.grafana.plugins | join "," }}
            - name: GF_PATHS_DATA
              value: /var/lib/grafana
            - name: GF_PATHS_LOGS
              value: /var/log/grafana
            - name: GF_PATHS_PLUGINS
              value: /var/lib/grafana/plugins
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
          volumeMounts:
            - name: config
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            - name: storage
              mountPath: /var/lib/grafana
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboards
              mountPath: /etc/grafana/provisioning/dashboards
            - name: alertmanager
              mountPath: /etc/grafana/provisioning/alertmanager
            - name: alertrules
              mountPath: /etc/grafana/provisioning/alertrules
          resources:
            {{- toYaml .Values.grafana.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "diagnostico.fullname" . }}-grafana
        - name: storage
          {{- if .Values.grafana.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "diagnostico.fullname" . }}-grafana
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: datasources
          configMap:
            name: {{ include "diagnostico.fullname" . }}-datasource
        - name: dashboards
          configMap:
            name: {{ include "diagnostico.fullname" . }}-dashboard
        - name: alertmanager
          configMap:
            name: {{ include "diagnostico.fullname" . }}-alertmanager
        - name: alertrules
          configMap:
            name: {{ include "diagnostico.fullname" . }}-alertrules
      {{- with .Values.grafana.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.grafana.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.grafana.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }} 