{{- if .Values.grafana.enabled }}
{{- if .Values.grafana.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "diagnostico.fullname" . }}-grafana
  labels:
    {{- include "diagnostico.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "diagnostico.fullname" . }}-grafana
  minReplicas: {{ .Values.grafana.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.grafana.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.grafana.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.grafana.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.grafana.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.grafana.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- if .Values.grafana.autoscaling.targetAverageValue }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: {{ .Values.grafana.autoscaling.targetAverageValue }}
    {{- end }}
    {{- if .Values.grafana.autoscaling.metrics }}
    {{- toYaml .Values.grafana.autoscaling.metrics | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }} 