apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoramento-config
  namespace: autocura
data:
  collection_interval: "15"
  retention_period_days: "7"
  anomaly_detection_sensitivity: "0.8"
  log_level: "INFO"
  metrics_interval: "30"
  enable_tracing: "true"
  tracing_endpoint: "http://jaeger-collector:14268/api/traces" 