apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autocura-models
  namespace: autocura
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autocura-templates
  namespace: autocura
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autocura-data
  namespace: autocura
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 