apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
<<<<<<< HEAD

resources:
- gateway.yaml
- virtualservice.yaml
- destinationrule.yaml 
=======
resources:
- gateway.yaml
- virtualservice.yaml
- destinationrule.yaml
>>>>>>> origin/main
