# Configuração da Camada de Integração

# Configurações dos adaptadores de comunicação
adaptadores:
  http:
    timeout: 30  # segundos
    retries: 3
    max_connections: 100
    keep_alive: true
    verify_ssl: true
    
  websocket:
    ping_interval: 20  # segundos
    ping_timeout: 10
    max_size: 1048576  # 1MB
    max_queue: 32
    
  redis:
    host: localhost
    port: 6379
    db: 0
    password: null
    socket_timeout: 5
    socket_connect_timeout: 5
    retry_on_timeout: true
    
  kafka:
    bootstrap_servers:
      - localhost:9092
    client_id: autocura_integracao
    group_id: autocura_group
    auto_offset_reset: latest
    enable_auto_commit: true
    auto_commit_interval_ms: 5000

# Configurações dos tradutores de formato
tradutores:
  json:
    indent: 2
    ensure_ascii: false
    sort_keys: true
    
  msgpack:
    use_bin_type: true
    strict_types: true
    
  yaml:
    default_flow_style: false
    sort_keys: true
    allow_unicode: true

# Configurações dos gateways de serviço
gateways:
  monitoramento:
    tipo: http
    endpoint: http://localhost:8001
    timeout: 30
    retries: 3
    
  diagnostico:
    tipo: websocket
    endpoint: ws://localhost:8002
    ping_interval: 20
    
  gerador_acoes:
    tipo: redis
    host: localhost
    port: 6379
    db: 1
    
  executor_acoes:
    tipo: kafka
    topico: acoes
    bootstrap_servers:
      - localhost:9092

# Configurações de segurança
seguranca:
  ssl:
    enabled: true
    cert_file: certs/cert.pem
    key_file: certs/key.pem
    ca_file: certs/ca.pem
    
  autenticacao:
    enabled: true
    tipo: jwt
    secret_key: ${JWT_SECRET_KEY}
    token_expire: 3600  # segundos
    
  autorizacao:
    enabled: true
    roles:
      - admin
      - operador
      - monitor

# Configurações de logging
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/integracao.log
  max_size: 10485760  # 10MB
  backup_count: 5

# Configurações de monitoramento
monitoramento:
  enabled: true
  metrics_port: 9090
  health_check_interval: 30  # segundos
  alert_threshold:
    error_rate: 0.01
    latency_ms: 1000
    queue_size: 1000

# Configurações de cache
cache:
  enabled: true
  type: redis
  ttl: 3600  # segundos
  max_size: 1000
  cleanup_interval: 300  # segundos 