# Configurações Globais
sistema:
  nome: "Autocura"
  versao: "1.0.0"
  ambiente: "desenvolvimento"
  log_level: "INFO"

# Configurações de Módulos
modulos:
  monitoramento:
    intervalo: 60
    metricas:
      - throughput
      - latencia
      - taxa_erro
      - uso_recursos
    alertas:
      threshold_critico: 0.9
      threshold_alerta: 0.7

  diagnostico:
    modelo: "neural"
    threshold: 0.8
    batch_size: 32
    retencao_historico: "30d"

  gerador:
    max_acoes: 10
    prioridade:
      - critica
      - alta
      - media
      - baixa
    timeout: 300

  guardiao:
    nivel_alerta: 0.7
    protocolos:
      - monitoramento_intensificado
      - acoes_corretivas
      - shutdown_gradual
    check_interval: 30

  observabilidade:
    retencao_dados: "30d"
    dashboard:
      refresh: "5s"
      graficos:
        - metricas_operacionais
        - metricas_cognitivas
        - metricas_eticas

  etica:
    categorias:
      - privacidade
      - transparencia
      - equidade
      - seguranca
    limites:
      vies: 0.1
      explicabilidade: 0.8

  memoria:
    cache:
      tamanho: "1GB"
      ttl: "1h"
    persistencia:
      tipo: "sqlite"
      path: "/app/memoria/db"

# Configurações de Infraestrutura
infraestrutura:
  kubernetes:
    namespace: "autocura"
    replicas:
      min: 3
      max: 10
    recursos:
      cpu:
        request: "100m"
        limit: "500m"
      memoria:
        request: "128Mi"
        limit: "512Mi"

  monitoramento:
    prometheus:
      scrape_interval: "15s"
      retention: "15d"
    grafana:
      refresh: "5s"
      retention: "30d"

# Configurações de Segurança
seguranca:
  autenticacao:
    tipo: "jwt"
    expiracao: "24h"
  criptografia:
    algoritmo: "AES-256"
    chave_rotacao: "7d"
  auditoria:
    retencao_logs: "365d"

# Configurações de Logging
logging:
  nivel: INFO
  formato: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  arquivo: "logs/sistema.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5

# Configurações de Memória
memoria:
  caminho: "memoria_compartilhada.json"
  backup_intervalo: 3600  # 1 hora
  retencao_dias: 30

# Configurações de Autonomia
autonomia:
  nivel_inicial: 1
  intervalo_verificacao: 300  # 5 minutos
  criterios_avanco:
    precisao_minima: 0.95
    falsos_negativos_maximos: 0
    tempo_operacao_minimo: 90  # dias
    incidentes_maximos: 0
    validacao_etica_requerida: true

# Configurações de Monitoramento
monitoramento:
  intervalo: 60  # 1 minuto
  metricas:
    cpu:
      limite_alerta: 80
      limite_critico: 90
    memoria:
      limite_alerta: 75
      limite_critico: 85
    latencia:
      limite_alerta: 500
      limite_critico: 1000

# Configurações de Validação Ética
etica:
  principios:
    - transparencia
    - privacidade
    - nao_maleficencia
    - justica
    - autonomia
  validacao_obrigatoria: true
  relatorio_intervalo: 86400  # 24 horas

# Configurações de Ações
acoes:
  max_pendentes: 10
  timeout_execucao: 300  # 5 minutos
  retry_intervalo: 60  # 1 minuto
  max_retries: 3

# Configurações de Salvaguardas
salvaguardas:
  reducao_autonomia:
    nivel_emergencia: 1
    duracao_minima: 3600  # 1 hora
  suspensao_operacoes:
    duracao_maxima: 86400  # 24 horas
    notificacao_obrigatoria: true

# Configurações de Aprendizado
aprendizado:
  coleta_intervalo: 300  # 5 minutos
  analise_intervalo: 3600  # 1 hora
  padroes_minimos: 3
  confianca_minima: 0.8

# Configurações de API
api:
  host: "0.0.0.0"
  porta: 8000
  debug: false
  cors:
    origens_permitidas:
      - "http://localhost:3000"
      - "https://app.autocura.com"
    metodos_permitidos:
      - GET
      - POST
      - PUT
      - DELETE
    headers_permitidos:
      - Content-Type
      - Authorization

# Configurações de Backup
backup:
  intervalo: 86400  # 24 horas
  retencao: 7  # dias
  destino: "backups/"
  compressao: true

# Configurações de Notificações
notificacoes:
  email:
    servidor: "smtp.gmail.com"
    porta: 587
    tls: true
    remetente: "sistema@autocura.com"
  slack:
    webhook_url: "https://hooks.slack.com/services/xxx/yyy/zzz"
    canal: "#alertas-sistema"
  telegram:
    bot_token: "123456789:ABCdefGHIjklMNOpqrsTUVwxyz"
    chat_id: "-1001234567890"

# Configurações de Integração
integracao:
  prometheus:
    habilitado: true
    porta: 9090
    path: "/metrics"
  grafana:
    habilitado: true
    porta: 3000
    path: "/grafana"
  elasticsearch:
    habilitado: true
    hosts:
      - "http://localhost:9200"
    indice_prefixo: "autocura-" 