# Configurações do Sistema AutoCura
# ===============================

# Configurações de Logging
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/autocura.log"
  max_size: 10485760  # 10MB
  backup_count: 5

# Configurações de Capacidades
capabilities:
  classical_computing:
    enabled: true
    version: "1.0.0"
    dependencies: []
  
  quantum_computing:
    enabled: false
    version: "0.1.0-alpha"
    dependencies:
      - classical_computing
    requirements:
      quantum_hardware: required
      quantum_software: required
  
  nano_technology:
    enabled: false
    version: "0.1.0-alpha"
    dependencies:
      - classical_computing
    requirements:
      nano_controllers: required
      nano_sensors: required
  
  bio_computing:
    enabled: false
    version: "0.1.0-alpha"
    dependencies:
      - classical_computing
    requirements:
      bio_interface: required
      bio_processors: required

# Configurações de Plugins
plugins:
  core:
    version: "1.0.0"
    enabled: true
    config:
      max_threads: 4
      timeout: 30
  
  quantum:
    version: "0.1.0-alpha"
    enabled: false
    config:
      quantum_backend: "simulator"
      max_qubits: 5
  
  nano:
    version: "0.1.0-alpha"
    enabled: false
    config:
      nano_controller: "simulator"
      max_devices: 10
  
  bio:
    version: "0.1.0-alpha"
    enabled: false
    config:
      bio_interface: "simulator"
      max_connections: 5

# Configurações de Versionamento
versioning:
  core:
    version: "1.0.0"
    type: "major"
    is_stable: true
  
  quantum:
    version: "0.1.0-alpha"
    type: "alpha"
    is_stable: false
  
  nano:
    version: "0.1.0-alpha"
    type: "alpha"
    is_stable: false
  
  bio:
    version: "0.1.0-alpha"
    type: "alpha"
    is_stable: false

# Configurações de Interface
interface:
  host: "localhost"
  port: 8000
  debug: false
  cors:
    enabled: true
    origins:
      - "http://localhost:3000"
      - "http://localhost:8080"
  
  api:
    version: "v1"
    prefix: "/api"
    docs: true
    redoc: true

# Configurações de Monitoramento
monitoring:
  enabled: true
  interval: 60  # segundos
  metrics:
    cpu: true
    memory: true
    disk: true
    network: true
  
  alerts:
    enabled: true
    channels:
      - type: "email"
        enabled: true
        recipients:
          - "admin@exemplo.com"
      - type: "slack"
        enabled: false
        webhook: "https://hooks.slack.com/services/xxx/yyy/zzz"

# Configurações de Segurança
security:
  authentication:
    enabled: true
    method: "jwt"
    secret: "your-secret-key"
    token_expiry: 3600  # segundos
  
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"
    key_rotation: 86400  # segundos
  
  audit:
    enabled: true
    log_file: "logs/audit.log"
    events:
      - "login"
      - "logout"
      - "capability_change"
      - "version_change"
      - "plugin_change"

# Configurações de Backup
backup:
  enabled: true
  schedule: "0 0 * * *"  # Diário à meia-noite
  retention: 7  # dias
  location: "backups/"
  compression: true
  encryption: true

# Configurações de Desenvolvimento
development:
  debug: false
  testing:
    enabled: true
    coverage:
      enabled: true
      threshold: 80
    mock:
      enabled: true
      quantum: true
      nano: true
      bio: true
  
  documentation:
    enabled: true
    format: "markdown"
    output: "docs/"
    auto_generate: true 