apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: autocura

resources:
- ../base/namespace.yaml
- ../base/deployment.yaml
- hpa.yaml
- network-policy.yaml
- pdb.yaml
- resource-quota.yaml
- limit-range.yaml
- rbac.yaml

configMapGenerator:
- name: autocura-config
  behavior: merge
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=INFO

patchesStrategicMerge:
- patches/network-policy.yaml
- patches/resource-limits.yaml

images:
- name: autocura/api
  newName: autocura/api
  newTag: latest
- name: autocura/monitor
  newName: autocura/monitor
  newTag: latest
- name: autocura/diagnostico
  newName: autocura/diagnostico
  newTag: latest
- name: autocura/gerador
  newName: autocura/gerador
  newTag: latest
- name: autocura/guardiao
  newName: autocura/guardiao
  newTag: latest
- name: autocura/observador
  newName: autocura/observador
  newTag: latest
- name: autocura/validador
  newName: autocura/validador
  newTag: latest 