apiVersion: v1
kind: ResourceQuota
metadata:
  name: autocura-quota
  namespace: autocura
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services.loadbalancers: "2"
    services.nodeports: "5"
    pods: "20" 