apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
<<<<<<< HEAD

namespace: autocura

=======
namespace: autocura
>>>>>>> origin/main
resources:
- prometheus.yaml
- grafana.yaml
- alertmanager.yaml
- alertmanager-config.yaml
- fluentd.yaml
- elasticsearch.yaml
- kibana.yaml
<<<<<<< HEAD

=======
>>>>>>> origin/main
labels:
- pairs:
    app.kubernetes.io/name: observabilidade
    app.kubernetes.io/part-of: autocura
<<<<<<< HEAD

commonAnnotations:
  description: "Configurações de observabilidade do Sistema de Autocura Cognitiva"
=======
commonAnnotations:
  description: Configurações de observabilidade do Sistema de Autocura Cognitiva
>>>>>>> origin/main
