apiVersion: v1
kind: Service
metadata:
  name: observabilidade
  namespace: autocura
  labels:
    app: observabilidade
    component: autocura
spec:
  selector:
    app: observabilidade
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP
