apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: "2025-05-04T21:33:49Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: alertmanager
  name: storage-prometheus-alertmanager-0
  namespace: autocura
  resourceVersion: "10392"
  uid: 22a9c803-1c70-4a78-baeb-572dc9961241
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
  volumeMode: Filesystem
status:
  phase: Pending 