apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollback-operator
  namespace: autocura
  labels:
    app: rollback-operator
    app.kubernetes.io/component: rollback-operator
    app.kubernetes.io/environment: development
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: autocura
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollback-operator
      app.kubernetes.io/component: rollback-operator
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: autocura
  template:
    metadata:
      labels:
        app: rollback-operator
        app.kubernetes.io/component: rollback-operator
        app.kubernetes.io/environment: development
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/part-of: autocura
        environment: development
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - rollback-operator
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - name: rollback-operator
        image: localhost:5000/autocura/rollback-operator:latest
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: rollback-operator
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      serviceAccountName: autocura-sa
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule 