global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'autocura_etica'
    static_configs:
      - targets: ['localhost:8000']
    metrics_path: '/metrics'
    scheme: 'http'
    
  - job_name: 'autocura_auditoria'
    static_configs:
      - targets: ['localhost:8001']
    metrics_path: '/metrics'
    scheme: 'http'
    
  - job_name: 'autocura_monitoramento'
    static_configs:
      - targets: ['localhost:8002']
    metrics_path: '/metrics'
    scheme: 'http' 