# Secret com dados sensíveis do AutoCura
# ATENÇÃO: Em produção, use ferramentas como Sealed Secrets ou HashiCorp Vault
apiVersion: v1
kind: Secret
metadata:
  name: autocura-secrets
  namespace: autocura-staging
type: Opaque
stringData:
  # Credenciais PostgreSQL
  POSTGRES_USER: "autocura"
  POSTGRES_PASSWORD: "autocura_staging_2024"  # MUDAR EM PRODUÇÃO!
  
  # Credenciais Redis
  REDIS_PASSWORD: "redis_staging_2024"  # MUDAR EM PRODUÇÃO!
  
  # API Keys (exemplo - substituir com valores reais)
  OPENAI_API_KEY: "sk-placeholder"  # SUBSTITUIR COM CHAVE REAL
  
  # JWT Secret para autenticação
  JWT_SECRET: "autocura_jwt_secret_staging_2024"  # GERAR NOVO EM PRODUÇÃO!
  
  # Grafana admin
  GRAFANA_ADMIN_USER: "admin"
  GRAFANA_ADMIN_PASSWORD: "autocura_grafana_2024"  # MUDAR EM PRODUÇÃO! 