apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base
- components/monitoramento
- components/diagnostico
- components/gerador
- components/observabilidade
- operators/healing-operator
- operators/rollback-operator
- storage
- deployment.yaml
- components/hpa.yaml
- monitoring/prometheus-config.yaml
- monitoring/grafana-dashboards.yaml
- monitoring/opentelemetry-config.yaml
- monitoring/opentelemetry-collector.yaml
- monitoring/grafana-business-metrics.yaml
- monitoring/loki-config.yaml
- monitoring/loki-deployment.yaml
- monitoring/grafana-logs-dashboard.yaml

commonLabels:
  app.kubernetes.io/part-of: autocura
  app.kubernetes.io/managed-by: kustomize
  app: autocura
  environment: production
  OTEL_ENABLED: "true"
  LOGGING_ENABLED: "true"

namespace: autocura

# Configurações de recursos e limites padrão para todos os pods
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

# Configurações de tolerância a falhas
podDisruptionBudget:
  minAvailable: 1

# Configuração para seleção de ambiente
# Descomente apenas um dos overlays abaixo para selecionar o ambiente desejado

# Para ambiente de desenvolvimento:
# patchesStrategicMerge:
# - environments/development/kustomization.yaml

# Para ambiente de staging:
# patchesStrategicMerge:
# - environments/staging/kustomization.yaml

# Para ambiente de produção:
# patchesStrategicMerge:
# - environments/production/kustomization.yaml

patches:
  - path: patches/security-context.yaml
  - path: patches/resource-limits.yaml
  - path: patches/resource-limits.yaml
    target:
      kind: Deployment
      name: autocura

configMapGenerator:
  - name: autocura-config
    behavior: merge
    literals:
      - LOG_LEVEL=INFO
      - ENVIRONMENT=production
      - METRICS_ENABLED=true
      - TRACING_ENABLED=true
      - OTEL_ENABLED=true

secretGenerator:
  - name: autocura-secrets
    envs:
      - .env
    type: Opaque

images:
  - name: autocura/api
    newName: autocura/api
    newTag: latest
  - name: autocura/monitor
    newName: autocura/monitor
    newTag: latest
  - name: autocura/diagnostico
    newName: autocura/diagnostico
    newTag: latest
  - name: autocura/gerador
    newName: autocura/gerador
    newTag: latest
  - name: autocura/guardiao
    newName: autocura/guardiao
    newTag: latest
  - name: autocura/observador
    newName: autocura/observador
    newTag: latest
  - name: autocura/validador
    newName: autocura/validador
    newTag: latest
