# Configurações de Monitoramento

# Configurações do Prometheus
prometheus:
  host: localhost
  port: 9090
  metrics:
    - nome: total_testes
      tipo: counter
      descricao: "Total de testes executados"
    - nome: testes_falha
      tipo: counter
      descricao: "Total de testes que falharam"
    - nome: duracao_testes
      tipo: histogram
      descricao: "Duração dos testes em segundos"
      buckets: [0.1, 0.5, 1.0, 2.0, 5.0, 10.0]
    - nome: cobertura_codigo
      tipo: gauge
      descricao: "Cobertura de código em porcentagem"

# Configurações do Grafana
grafana:
  host: localhost
  port: 3000
  dashboards:
    - nome: "Testes"
      descricao: "Dashboard de monitoramento de testes"
      paineis:
        - titulo: "Total de Testes"
          tipo: "graph"
          metricas: ["total_testes"]
        - titulo: "Falhas"
          tipo: "graph"
          metricas: ["testes_falha"]
        - titulo: "Duração"
          tipo: "heatmap"
          metricas: ["duracao_testes"]
        - titulo: "Cobertura"
          tipo: "gauge"
          metricas: ["cobertura_codigo"]

# Configurações de Alertas
alertas:
  prometheus:
    regras:
      - nome: "Alta Taxa de Falhas"
        expr: "rate(testes_falha[5m]) > 0.1"
        for: "5m"
        labels:
          severity: "warning"
        annotations:
          summary: "Alta taxa de falhas nos testes"
          description: "Taxa de falhas acima de 10% nos últimos 5 minutos"
          
      - nome: "Cobertura Baixa"
        expr: "cobertura_codigo < 80"
        for: "1h"
        labels:
          severity: "critical"
        annotations:
          summary: "Cobertura de código abaixo do esperado"
          description: "Cobertura de código abaixo de 80% por mais de 1 hora"

# Configurações de Notificações
notificacoes:
  email:
    smtp:
      host: smtp.gmail.com
      port: 587
      usuario: ${SMTP_USER}
      senha: ${SMTP_PASSWORD}
    destinatarios:
      - "equipe@exemplo.com"
      - "qa@exemplo.com"
    template:
      assunto: "[ALERTA] {severity} - {summary}"
      corpo: |
        Alerta: {summary}
        Descrição: {description}
        Severidade: {severity}
        Timestamp: {timestamp}
        
  slack:
    webhook_url: ${SLACK_WEBHOOK_URL}
    canal: "#alertas-testes"
    template:
      cor: |
        {% if severity == 'critical' %}
        #FF0000
        {% elif severity == 'warning' %}
        #FFA500
        {% else %}
        #00FF00
        {% endif %}
      mensagem: |
        *{summary}*
        {description}
        Severidade: {severity}
        Timestamp: {timestamp}

# Configurações de Logging
logging:
  nivel: INFO
  formato: "%(asctime)s [%(levelname)s] %(message)s"
  data: "%Y-%m-%d %H:%M:%S"
  arquivo: "logs/monitoramento.log"
  max_bytes: 10485760  # 10MB
  backup_count: 5

# Configurações de Retenção
retencao:
  prometheus:
    tempo: "15d"
  grafana:
    tempo: "30d"
  logs:
    tempo: "90d" 