apiVersion: v1
kind: PersistentVolumeClaim
metadata:
<<<<<<< HEAD
  name: data-pvc
=======
  name: autocura-data
>>>>>>> origin/main
  namespace: autocura
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi 