version: '3.8'

services:
  # API Principal com Dashboard
  autocura-api:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile.api
    container_name: autocura-api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=INFO
      - HOST=0.0.0.0
      - PORT=8000
      - RELOAD=false
    volumes:
      - ../../src:/app/src
      - ../../dashboard.html:/app/dashboard.html
      - ../../memoria_compartilhada.json:/app/memoria_compartilhada.json
      - ../../data:/app/data
    networks:
      - autocura-network
    depends_on:
      - autocura-redis

  # Redis para cache e mensageria
  autocura-redis:
    image: redis:alpine
    container_name: autocura-redis
    ports:
      - "6379:6379"
    networks:
      - autocura-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  autocura-network:
    driver: bridge 