# Configurações de Monitoramento

# Prometheus
prometheus:
  habilitado: true
  host: "localhost"
  porta: 9090
  prefixo_metricas: "autocura_testes_"
  intervalos_coleta: 15  # segundos
  metricas:
    - nome: "testes_executados_total"
      tipo: "counter"
      descricao: "Total de testes executados"
    - nome: "testes_falhas_total"
      tipo: "counter"
      descricao: "Total de falhas em testes"
    - nome: "duracao_testes_segundos"
      tipo: "histogram"
      descricao: "Duração dos testes em segundos"
    - nome: "cobertura_codigo_percentual"
      tipo: "gauge"
      descricao: "Cobertura de código em percentual"

# Grafana
grafana:
  habilitado: true
  host: "localhost"
  porta: 3000
  api_key: ""  # Configurar via variável de ambiente
  dashboards:
    - nome: "Testes Autocura"
      uid: "autocura-testes"
      paineis:
        - titulo: "Execução de Testes"
          tipo: "graph"
          metricas: ["testes_executados_total", "testes_falhas_total"]
        - titulo: "Duração dos Testes"
          tipo: "heatmap"
          metricas: ["duracao_testes_segundos"]
        - titulo: "Cobertura de Código"
          tipo: "gauge"
          metricas: ["cobertura_codigo_percentual"]

# ELK Stack
elk:
  habilitado: true
  elasticsearch:
    host: "localhost"
    porta: 9200
    indice_prefixo: "autocura-testes-"
  logstash:
    host: "localhost"
    porta: 5044
  kibana:
    host: "localhost"
    porta: 5601

# Alertas
alertas:
  prometheus:
    regras:
      - nome: "AltaTaxaFalhas"
        condicao: "rate(testes_falhas_total[5m]) > 0.1"
        duracao: "5m"
        severidade: "critical"
        anotacoes:
          resumo: "Alta taxa de falhas nos testes"
          descricao: "Mais de 10% dos testes estão falhando"
      
      - nome: "BaixaCobertura"
        condicao: "cobertura_codigo_percentual < 80"
        duracao: "1h"
        severidade: "warning"
        anotacoes:
          resumo: "Cobertura de código abaixo do esperado"
          descricao: "Cobertura de código está abaixo de 80%"
  
  email:
    smtp:
      servidor: "smtp.gmail.com"
      porta: 587
      usuario: ""  # Configurar via variável de ambiente
      senha: ""    # Configurar via variável de ambiente
    destinatarios:
      - "equipe@exemplo.com"
      - "devops@exemplo.com"
  
  slack:
    webhook_url: ""  # Configurar via variável de ambiente
    canal: "#alertas-testes"
    icones:
      critical: ":red_circle:"
      warning: ":yellow_circle:"
      info: ":blue_circle:"

# Logging
logging:
  nivel: "INFO"
  formato: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  arquivo: "logs/monitoramento.log"
  rotacao:
    max_bytes: 10485760  # 10MB
    backup_count: 5
  elasticsearch:
    habilitado: true
    indice: "autocura-testes-logs"
    nivel_minimo: "WARNING" 