# Configurações do Automatizador de Testes

# Configurações gerais
cobertura_minima: 80  # Porcentagem mínima de cobertura de código
timeout: 300  # Timeout em segundos para testes de integração

# Configurações de logging
logging:
  level: INFO
  formato: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  arquivo: "logs/testes.log"

# Configurações de relatórios
relatorios:
  diretorio: "relatorios"
  formato: "markdown"
  incluir_cobertura: true
  incluir_metricas: true

# Configurações de notificações
notificacoes:
  email:
    habilitado: false
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    remetente: "testes@exemplo.com"
    destinatarios: []
  
  slack:
    habilitado: false
    webhook_url: ""
    canal: "#testes"

# Configurações de ambiente
ambiente:
  variaveis:
    TEST_DB_URL: "postgresql://test:test@localhost:5432/test_db"
    TEST_REDIS_URL: "redis://localhost:6379/0"
    TEST_API_URL: "http://localhost:8000"

# Configurações de execução
execucao:
  paralela: true
  max_workers: 4
  retry_failed: true
  max_retries: 3
  ordenar_por: "duracao"  # duracao, nome, cobertura 