apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "[autocura-]YYYY.MM.DD"
    jsonData:
      timeField: "@timestamp"
      esVersion: 7.15.0
      interval: Daily
    editable: false

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: false

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: autocura
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
    editable: false 