repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: debug-statements

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
        language_version: python3.9

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-docstrings',
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-simplify',
            'flake8-import-order',
            'flake8-quotes',
            'flake8-print',
            'flake8-debugger',
            'flake8-eradicate',
            'flake8-mutable',
            'flake8-multiline-containers',
            'flake8-pie',
            'flake8-return',
            'flake8-super',
            'flake8-tidy-imports',
            'flake8-unused-arguments',
            'flake8-variables-names',
            'flake8-builtins',
            'flake8-commas',
            'flake8-comprehensions',
            'flake8-docstrings',
            'flake8-import-order',
            'flake8-quotes',
            'flake8-string-format',
            'flake8-todo',
            'flake8-variables-names',
        ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
    -   id: mypy
        additional_dependencies: [
            'types-all',
            'pydantic',
            'fastapi',
            'uvicorn',
            'aiohttp',
            'pytest',
            'pytest-asyncio',
            'pytest-cov',
        ]

-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.6
    hooks:
    -   id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.6
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
    -   id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, scss, md, yaml, yml]

-   repo: https://github.com/crate-ci/typos
    rev: v1.16.26
    hooks:
    -   id: typos

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.12.0
    hooks:
    -   id: commitizen
        stages: [commit-msg] 