apiVersion: apps/v1
kind: Deployment
metadata:
  name: healing-operator
  namespace: autocura
  labels:
    app: healing-operator
    component: autocura
    app.kubernetes.io/component: healing-operator
    app.kubernetes.io/part-of: autocura
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healing-operator
  template:
    metadata:
      labels:
        app: healing-operator
    spec:
      serviceAccountName: autocura-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: healing-operator
<<<<<<< HEAD
        image: localhost:5000/autocura/healing-operator:latest
=======
        image: registry.registry.svc.cluster.local:5000/autocura/healing-operator:latest
>>>>>>> origin/main
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "healing-operator"
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - healing-operator
              topologyKey: "kubernetes.io/hostname"
