global:
  resolve_timeout: 5m
  slack_api_url: 'https://hooks.slack.com/services/YOUR_SLACK_WEBHOOK_URL'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'slack-critical'
      continue: true
    - match:
        severity: warning
      receiver: 'slack-warning'
      continue: true

receivers:
  - name: 'slack-notifications'
    slack_configs:
      - channel: '#monitoring'
        send_resolved: true
        title: '{{ template "slack.default.title" . }}'
        text: '{{ template "slack.default.text" . }}'
        actions:
          - type: button
            text: 'View Dashboard'
            url: '{{ template "slack.default.dashboardurl" . }}'
          - type: button
            text: 'View Logs'
            url: '{{ template "slack.default.logsurl" . }}'

  - name: 'slack-critical'
    slack_configs:
      - channel: '#critical-alerts'
        send_resolved: true
        title: '{{ template "slack.critical.title" . }}'
        text: '{{ template "slack.critical.text" . }}'
        actions:
          - type: button
            text: 'View Dashboard'
            url: '{{ template "slack.critical.dashboardurl" . }}'
          - type: button
            text: 'View Logs'
            url: '{{ template "slack.critical.logsurl" . }}'

  - name: 'slack-warning'
    slack_configs:
      - channel: '#warning-alerts'
        send_resolved: true
        title: '{{ template "slack.warning.title" . }}'
        text: '{{ template "slack.warning.text" . }}'
        actions:
          - type: button
            text: 'View Dashboard'
            url: '{{ template "slack.warning.dashboardurl" . }}'
          - type: button
            text: 'View Logs'
            url: '{{ template "slack.warning.logsurl" . }}'

templates:
  - '/etc/alertmanager/templates/*.tmpl' 