// Package v1 contains API Schema definitions for the healing v1 API group
// +kubebuilder:object:generate=true
// +groupName=healing.autocura.io
package v1

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Healing) DeepCopyInto(out *Healing) {
	*out = *in
	// Placeholder: Implement deep copy logic if your HealingSpec or HealingStatus have complex types (slices, maps, pointers to structs)
	// For example:
	// if in.Spec.Selector != nil {
	// 	out.Spec.Selector = new(metav1.LabelSelector)
	// 	in.Spec.Selector.DeepCopyInto(out.Spec.Selector)
	// }
	// out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Healing.
func (in *Healing) DeepCopy() *Healing {
	if in == nil {
		return nil
	}
	out := new(Healing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Healing) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealingList) DeepCopyInto(out *HealingList) {
	*out = *in
	// Placeholder: Implement deep copy logic for Items
	// if in.Items != nil {
	// 	in, out := &in.Items, &out.Items
	// 	*out = make([]Healing, len(*in))
	// 	for i := range *in {
	// 		(*in)[i].DeepCopyInto(&(*out)[i])
	// 	}
	// }
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealingList.
func (in *HealingList) DeepCopy() *HealingList {
	if in == nil {
		return nil
	}
	out := new(HealingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HealingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealingSpec) DeepCopyInto(out *HealingSpec) {
	*out = *in
	// Placeholder for HealingSpec deepcopy logic
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealingSpec.
func (in *HealingSpec) DeepCopy() *HealingSpec {
	if in == nil {
		return nil
	}
	out := new(HealingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealingStatus) DeepCopyInto(out *HealingStatus) {
	*out = *in
	// Placeholder for HealingStatus deepcopy logic
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealingStatus.
func (in *HealingStatus) DeepCopy() *HealingStatus {
	if in == nil {
		return nil
	}
	out := new(HealingStatus)
	in.DeepCopyInto(out)
	return out
}

