# charts/ConscienciaSituacional/values.yaml

replicaCount: 1

image:
  repository: seu-registro/consciencia-situacional-service # Substitua pelo seu repositório de imagem Docker
  pullPolicy: IfNotPresent
  tag: "latest" # Ou uma tag específica da versão

service:
  type: ClusterIP
  port: 80 # Porta do serviço Kubernetes (não exposta externamente por padrão)
  # targetPort: 5000 # Porta onde o container está escutando (se for um serviço HTTP, não aplicável para Kafka puro)

kafka:
  broker_url: "kafka.default.svc.cluster.local:9092" # Endereço do broker Kafka no cluster
  # Se estiver fora do cluster, use o endereço acessível

redis:
  enabled: true
  host: "redis-master.default.svc.cluster.local" # Exemplo de host do Redis no cluster
  port: 6379
  # password_secret: "redis-password-secret" # Nome do secret do K8s para a senha do Redis, se houver

# Configurações da integração web, podem ser sobrescritas no deploy
web_integration:
  enabled: true
  apis:
    news:
      # endpoint: "https://news.provider.org/v2" # Endpoint pode ser definido aqui ou vir de ConfigMap
      key_secret_name: "news-api-key-secret" # Nome do Secret do K8s contendo a NEWS_API_KEY
      rate_limit: "50/min" # Informativo, lógica de rate limit no app
    finance:
      # endpoint: "https://api.finance-data.com/v1/indicators"
      key_secret_name: "finance-api-key-secret"
      refresh_interval: "30m"
    climate:
      # endpoint: "https://api.climate-service.com/v4/climate"
      key_secret_name: "climate-api-key-secret"
  security:
    ssl_verify: true
    data_sanitization: "strict"

# Variáveis de ambiente adicionais que podem ser injetadas
environment_vars:
  LOG_LEVEL: "INFO"
  # NEWS_API_ENDPOINT: "https://news.provider.org/v2" # Pode ser injetado diretamente ou via ConfigMap
  # FINANCE_API_ENDPOINT: "https://api.finance-data.com/v1/indicators"
  # CLIMATE_API_ENDPOINT: "https://api.climate-service.com/v4/climate"

# Configuração de recursos para o pod
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

# Configuração para ConfigMaps e Secrets
# Se os endpoints das APIs forem gerenciados via ConfigMap
api_configmap_name: "consciencia-api-endpoints" # Nome do ConfigMap para endpoints

# Whitelist configuration
whitelist_configmap_name: "consciencia-whitelist-config" # Nome do ConfigMap para whitelist.yaml

# Se o conteúdo de api_endpoints.yaml e whitelist.yaml for gerenciado via ConfigMap
# e montado como arquivos no pod, os caminhos no código devem refletir isso.

# Exemplo de como as chaves de API seriam montadas a partir de Secrets:
# envFrom:
#   - secretRef:
#       name: news-api-key-secret
#   - secretRef:
#       name: finance-api-key-secret
#   - secretRef:
#       name: climate-api-key-secret

