services:
  # API Principal
  api:
    build:
      context: ../../..
      dockerfile: docker/environments/dev/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - AI_API_KEY=${AI_API_KEY}
      - OPENAI_API_KEY=${AI_API_KEY}
      - HOST=0.0.0.0
      - PORT=8000
    depends_on:
      - redis
    restart: unless-stopped

  # Cache Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-storage:/data
    restart: unless-stopped

volumes:
  redis-storage:

networks:
  default:
    name: autocura-dev 