apiVersion: v1
kind: Service
metadata:
  name: executor-acoes
  namespace: autocura
spec:
  selector:
    app: executor-acoes
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP 