apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: autocura

resources:
- healing-operator/
- rollback-operator/

commonLabels:
  app.kubernetes.io/name: operators
  app.kubernetes.io/part-of: autocura

commonAnnotations:
  description: "Configurações dos operadores para o Sistema de Autocura Cognitiva"

# Configurações de recursos para operadores
resources:
  requests:
    cpu: "200m"
    memory: "256Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

# Configurações de tolerância a falhas
podDisruptionBudget:
  minAvailable: 1

# Configurações de healthcheck
livenessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /readyz
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
