# Will Trading System Configuration

# API Keys (to be loaded from environment variables)
api_keys:
  news_api: ${NEWS_API_KEY}
  gemini_api: ${GEMINI_API_KEY}
  binance_api: ${BINANCE_API_KEY}
  binance_secret: ${BINANCE_SECRET_KEY}

# Trading Configuration
trading:
  # Trading pairs to monitor
  pairs:
    - EUR/USD
    - GBP/USD
    - USD/JPY
    - AUD/USD
    - USD/CAD
  
  # Risk Management
  risk:
    max_position_size: 0.02  # 2% of portfolio
    max_daily_loss: 0.05    # 5% of portfolio
    stop_loss: 0.01         # 1% per trade
    take_profit: 0.02       # 2% per trade
  
  # Technical Analysis
  technical:
    indicators:
      - name: RSI
        period: 14
        overbought: 70
        oversold: 30
      - name: MACD
        fast_period: 12
        slow_period: 26
        signal_period: 9
      - name: Bollinger Bands
        period: 20
        std_dev: 2

# News Analysis
news:
  sources:
    - Reuters
    - Bloomberg
    - Financial Times
    - Wall Street Journal
  update_interval: 300  # 5 minutes
  sentiment_threshold: 0.6

# Machine Learning
ml:
  model:
    type: LSTM
    layers: [64, 32, 16]
    dropout: 0.2
    batch_size: 32
    epochs: 100
  
  training:
    validation_split: 0.2
    early_stopping_patience: 10
    learning_rate: 0.001

# Monitoring
monitoring:
  metrics:
    - trading_performance
    - model_accuracy
    - system_health
    - risk_metrics
  
  alerts:
    telegram:
      enabled: true
      chat_id: ${TELEGRAM_CHAT_ID}
    email:
      enabled: false
      recipients: []

# Database
database:
  type: mongodb
  host: ${MONGODB_HOST}
  port: ${MONGODB_PORT}
  name: will_trading
  collections:
    trades: trades
    models: models
    metrics: metrics

# Logging
logging:
  level: INFO
  format: json
  handlers:
    - type: file
      filename: will.log
    - type: elasticsearch
      host: ${ELASTICSEARCH_HOST}
      port: ${ELASTICSEARCH_PORT}
      index: will-logs

# Security
security:
  encryption:
    enabled: true
    algorithm: AES-256-GCM
  rate_limiting:
    enabled: true
    requests_per_minute: 60
  ip_whitelist:
    enabled: true
    addresses: [] 