global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "autocura"
    metrics_path: "/metrics"
    scrape_interval: 5s
    static_configs:
      - targets: ["app:8000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: "([^:]+):.*"
        replacement: "${1}"

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "kube-state-metrics"
    static_configs:
      - targets: ["kube-state-metrics:8080"]

  - job_name: "blackbox"
    metrics_path: /metrics
    static_configs:
      - targets: ["blackbox-exporter:9115"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: "dependencias"
    static_configs:
      - targets: ["localhost:9092"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"] 