apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: consciencia-situacional
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: consciencia-situacional
  endpoints:
  - port: http
    interval: 15s
    scrapeTimeout: 10s
    path: /metrics
  namespaceSelector:
    matchNames:
      - default 